version: 1
disable_existing_loggers: False
formatters:
  access:
    "()": uvicorn.logging.AccessFormatter
    fmt: '%(asctime)s [%(levelname)s] %(client_addr)s - "%(request_line)s" %(status_code)s'
  default:
    "()": uvicorn.logging.DefaultFormatter
    fmt: '%(asctime)s [%(levelname)s] %(message)s'
handlers:
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
loggers:
  uvicorn.access:
    handlers: [access]
    level: INFO
    propagate: no
  uvicorn.error:
    handlers: [default]
    level: INFO
    propagate: no

